### ISSUE TITLE
wall-ink-server running https

### ISSUE THREAD

**Issue by zhongshanliyu** [caedm/wall-ink#21]
when wall-ink-server running https, the wall-ink get error message when get https://example.com/get_image.php.

**Comment by zhongshanliyu** [comment]
there are a example to showing the HTTPSRequest, i thiank that can solve the issue.

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino

**Comment by zhongshanliyu** [comment]
error code wall-ink-server logs below 

Firmware: 4.02a Width: 640 Height: 384 Voltage: 2.85 Error Code: 4294967295 Plugin: 1

**Comment by Pillmayr** [comment]
Hello. As you said before briefly: The firmware does not use the Secure Client but the normal Wifi client. I would simply customize the firmware in your place and use the Secure Client instead of the normal client: https://github.com/caedm/wall-ink/blob/master/stream_screen/stream_screen.ino#L730
The second option would be to instantiate the client based on the protocol. But I think that the first variant is more pragmatic and faster to implement, because all of your endpoints are running on HTTPS anyway, right?

**Comment by jdeananderson** [comment]
We investigated using an https client, but if I remember correctly there was not enough free memory in the sketch on the esp8266 to support it.  Perhaps Johnathan remembers?

**Comment by zhongshanliyu** [comment]
> Hello. As you said before briefly: The firmware does not use the Secure Client but the normal Wifi client. I would simply customize the firmware in your place and use the Secure Client instead of the normal client: https://github.com/caedm/wall-ink/blob/master/stream_screen/stream_screen.ino#L730
> The second option would be to instantiate the client based on the protocol. But I think that the first variant is more pragmatic and faster to implement, because all of your endpoints are running on HTTPS anyway, right?

correct, wall-ink-server running internet, and wall-ink get https url will encrypt the mac address etc.

**Comment by zhongshanliyu** [comment]
![Screenshot_23](https://user-images.githubusercontent.com/54261373/64477788-862c0280-d154-11e9-8e8d-d145febac0a7.png)
that true, memory not enough to running.
