### ISSUE TITLE
Upgrade to ESP32?

### ISSUE THREAD

**Issue by oldjohngalt** [caedm/wall-ink#26]
I am new to this, but with the memory limitations to the higher resolution 7.5 displays would it be feasible to switch to the ESP32?  This extra memory should help allow https for increased security and allow compression which may decrease the download time.

There seems to be some work being done at https://github.com/martinberlin/eink-calendar with the ESP32 and newer E-Ink Screens.

**Comment by jdeananderson** [comment]
We originally wanted to use the ESP32 for this project for all of the reasons you stated.   We even made a prototype and got it working... unreliably.  The ESP32 has a bug where it occasionally doesn't wake from deep sleep.  See https://esp32.com/viewtopic.php?f=12&t=12690.  We tried to make the ESP32 work, but we simply couldn't get it to wake up reliably.  When this bug in the ESP32 is fixed, we can work to move the project to the ESP32.  Moving the code over should not be that big of a deal. I just checked, and as of 8 days ago the deep sleep bug was still active.  

We built these devices for use in an enterprise, with 80+ devices deployed across several buildings and didn't want to deal with devices locking up and not booting.  Thanks for the suggestion, and I hope that we can go down that path soon.  Unfortunately, that bug has been around for two years and there does not seem to be a fix coming soon.  I could easily see a newer processor replacing the ESP32 being released before this bug is fixed.  We shall see, and I hope I am wrong...
