### ISSUE TITLE
DEFAULT_IMAGE_KEY not writing to memory when changed in Firmware

### ISSUE THREAD

**Issue by emdarcher** [caedm/wall-ink#3]
In the code I changed the value of DEFAULT_IMAGE_KEY in stream_screen.ino, compiled, and re-flashed the firmware with said code. When the device reboots it still uses the old image key. Tested by entering the web interface in admin mode to view the image key. When the image key was changed via the web interface it saved the new key to memory.
Tried rebooting in various ways, including removal and replacement of the battery. Issue persists.
Other values changed, such as ADMIN_PASSWORD are changed correctly when edited in the Firmware code.

**Comment by AndersenJ** [comment]
The image key is stored in the EEPROM, which persists even when the ESP8266 is flashed. To clear the EEPROM, run the ```eeprom_clear``` sketch. I added some documentation to the new Troubleshooting wiki page with details about that.

Because I know of no way for the device to know if it's just been flashed, I can't fix this and we'll just need to live with this workaround. Sorry.
